ca:
  common_name: str()
  organization: str()
  organization_unit: str()
  country: str()
  state: str()
  locality: str()
  email: str()
  key:
    algorithm: enum('RSA', 'EC')
    size: int(min=2048)
  validity:
    days: int(min=1, required=False)
    years: int(min=1, required=False)
  password:
    min_length: int(min=8)
    file: str(required=False)
    env_var: str(required=False)