ca:
  common_name: str()
  organization: str()
  organization_unit: str()
  country: str()
  state: str()
  locality: str()
  email: str()
  key_algorithm: enum('RSA2048', 'RSA3072', 'RSA4096', 'ECP256', 'ECP384', 'ECP521', 'ED25519', 'ED448')
  hash_algorithm: enum('SHA256', 'SHA384', 'SHA512', required=False)
  validity:
    days: int(min=1, required=False)
    years: int(min=1, required=False)
  password:
    min_length: int(min=8)
    file: str(required=False)
    env_var: str(required=False)