ca:
  common_name: "Reactor CA"
  organization: "Reactor Homelab"
  organization_unit: "IT"
  country: "DE"
  state: "Berlin"
  locality: "Berlin"
  email: "admin@example.com"
  key_algorithm: "RSA4096"  # Options: RSA2048, RSA3072, RSA4096, ECP256, ECP384, ECP521, ED25519, ED448
  hash_algorithm: "SHA256"  # Options: SHA256, SHA384, SHA512
  validity:
    years: 10
  password:
    min_length: 12
    # Session caching is always enabled