hosts:
  - name: "server1.example.com"
    common_name: "server1.example.com"
    alternative_names:
      dns:
        - "www.example.com"
        - "api.example.com"
      ip:
        - "192.168.1.10"
    export:
      cert: "../path/to/export/cert/server1.pem"
      chain: "../path/to/export/cert/server1-chain.pem"
    deploy:
      command: "systemctl reload nginx"
    validity:
      years: 1
    key:
      algorithm: "RSA"
      size: 2048