hosts:
  - name: "server1.example.com"
    common_name: "server1.example.com"
    alternative_names:
      dns:
        - "www.example.com"
        - "api.example.com"
      ip:
        - "192.168.1.10"
    export:
      cert: "../path/to/export/cert/server1.pem"
      chain: "../path/to/export/cert/server1-chain.pem"
    deploy:
      command: "systemctl reload nginx"
    validity:
      years: 1
    key:
      algorithm: "RSA"
      size: 2048
    hash_algorithm: "SHA256"  # Options: SHA256, SHA384, SHA512
  
  - name: "vpn.example.com"
    common_name: "vpn.example.com"
    alternative_names:
      dns:
        - "vpn.example.com"
      ip:
        - "192.168.1.100"
        - "2001:db8::1"  # IPv6 example
      email:
        - "admin@example.com"  # Email SAN
      uri:
        - "https://vpn.example.com"  # URI SAN
    validity:
      days: 365
    key:
      algorithm: "EC"
      size: "P384"  # EC curve name
    hash_algorithm: "SHA384"  # Using stronger hash
  
  - name: "auth.example.com"
    common_name: "auth.example.com"
    alternative_names:
      dns:
        - "auth.example.com"
        - "login.example.com"
      directory_name:
        - "CN=auth,O=Example Inc,C=US"  # Directory Name SAN
      registered_id:
        - "1.3.6.1.4.1.311.20.2.3"  # Example OID
    validity:
      years: 2
    key:
      algorithm: "ED25519"  # Using Ed25519
    hash_algorithm: "SHA512"  # Using strongest hash
    
  - name: "iot.example.com"
    common_name: "iot.example.com"
    alternative_names:
      dns:
        - "iot.example.com"
      ip:
        - "192.168.1.200"
      other_name:
        - "1.3.6.1.4.1.311.20.2.3:IoT Device"  # Custom OID with value
    validity:
      years: 3
    key:
      algorithm: "ED448"  # Using Ed448