name: Browser Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  test-https:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1-noble
      env:
        HOME: /root
        KEY_ALGORITHMS: "RSA2048 RSA3072 RSA4096 ECP256 ECP384 ECP521 ED25519"
        HASH_ALGORITHMS: "SHA256 SHA512"
    strategy:
      matrix:
        # Test all combinations of browsers with certificate algorithms
        browser: [curl, chromium, firefox, webkit]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Configure git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Setup Node.js
        if: matrix.browser != 'curl'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright dependency
        if: matrix.browser != 'curl'
        run: |
          npm init -y
          npm install --save-dev playwright@latest

      - name: Install Caddy
        run: |
          apt update
          apt install -y caddy

      - name: Build ReactorCA
        run: just build

      - name: Create test directory structure
        run: |
          mkdir -p /var/lib/test/caddy/site
          mkdir -p /var/lib/test/certs

      - name: Create test HTML page
        run: |
          cat > /var/lib/test/caddy/site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>ReactorCA HTTPS Test</title>
              <style>
                  body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
                  .success { color: green; }
                  .cert-info { background: #f0f0f0; padding: 20px; margin: 20px; border-radius: 5px; }
              </style>
          </head>
          <body>
              <h1 class="success">HTTPS Working!</h1>
              <p>ReactorCA self-signed certificate is working correctly.</p>
              <div class="cert-info">
                  <h3>Certificate Information</h3>
                  <p>This page is served over HTTPS using a certificate generated by ReactorCA.</p>
                  <p>Domain: localhost</p>
                  <p>Generated: <span id="timestamp"></span></p>
              </div>
              <script>
                  document.getElementById('timestamp').textContent = new Date().toISOString();
              </script>
          </body>
          </html>
          EOF

      - name: Initialize ReactorCA
        env:
          REACTOR_CA_PASSWORD: "test-password-123"
        run: |
          cd /var/lib/test
          $GITHUB_WORKSPACE/ca init

      - name: Configure ReactorCA for all certificate combinations
        run: |
          cd /var/lib/test

          # Ensure CA config has env_var set for password-based encryption
          if grep -q "provider: password" config/ca.yaml; then
            # Add env_var if using password provider and it's missing
            if ! grep -q "env_var:" config/ca.yaml; then
              sed -i '/min_length:/a\    env_var: REACTOR_CA_PASSWORD' config/ca.yaml
            fi
          fi

          # Create hosts.yaml with all certificate algorithm combinations using loops
          echo "=== Creating hosts.yaml with algorithm combinations ==="
          echo "KEY_ALGORITHMS: $KEY_ALGORITHMS"
          echo "HASH_ALGORITHMS: $HASH_ALGORITHMS"

          echo "hosts:" > config/hosts.yaml

          for key_algo in $KEY_ALGORITHMS; do
            for hash_algo in $HASH_ALGORITHMS; do
              cert_name=$(echo "${key_algo}-${hash_algo}" | tr '[:upper:]' '[:lower:]')
              echo "Generating config for: $cert_name (${key_algo} + ${hash_algo})"

              cat >> config/hosts.yaml << EOF
            ${cert_name}:
              alternative_names:
                dns:
                  - ${cert_name}.localhost
                  - 127.0.0.1
                ip:
                  - 127.0.0.1
                  - ::1
              validity:
                years: 1
              key_algorithm: ${key_algo}
              hash_algorithm: ${hash_algo}
              export:
                cert: "/var/lib/test/certs/${cert_name}.crt"
                chain: "/var/lib/test/certs/${cert_name}-chain.crt"
                key_encrypted: "/var/lib/test/certs/${cert_name}.key.age"

          EOF
            done
          done

          echo "=== Generated hosts.yaml content ==="
          cat config/hosts.yaml
          echo "=== End of hosts.yaml ==="

      - name: Create CA certificate
        env:
          REACTOR_CA_PASSWORD: "test-password-123"
        run: |
          cd /var/lib/test
          $GITHUB_WORKSPACE/ca ca create

      - name: Issue all certificates
        env:
          REACTOR_CA_PASSWORD: "test-password-123"
        run: |
          cd /var/lib/test
          echo "Creating all certificate combinations..."
          $GITHUB_WORKSPACE/ca host issue --all

      - name: Export private keys for Caddy
        env:
          REACTOR_CA_PASSWORD: "test-password-123"
        run: |
          cd /var/lib/test
          echo "Exporting private keys for all certificates..."

          # Export all private keys for Caddy using loops
          for key_algo in $KEY_ALGORITHMS; do
            for hash_algo in $HASH_ALGORITHMS; do
              cert_name=$(echo "${key_algo}-${hash_algo}" | tr '[:upper:]' '[:lower:]')
              echo "Exporting $cert_name private key..."
              $GITHUB_WORKSPACE/ca host export-key $cert_name -o /var/lib/test/certs/$cert_name.key
            done
          done

      - name: Install required packages
        run: |
          cd /var/lib/test

          # Install jq for all browsers (needed for JSON processing)
          apt-get update
          apt-get install -y jq

      - name: Install CA certificate in system trust store
        if: matrix.browser != 'curl'
        run: |
          cd /var/lib/test

          # Install NSS tools and p11-kit for certificate management
          apt-get install -y ca-certificates libnss3-tools p11-kit p11-kit-modules

          # Install CA cert in system trust store
          cp store/ca/ca.crt /usr/local/share/ca-certificates/reactorca-test.crt
          update-ca-certificates

          # Set NODE_EXTRA_CA_CERTS for Node.js/Playwright
          echo "NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV

          # Configure NSS database for Chromium (uses sql: format)
          mkdir -p $HOME/.pki/nssdb
          certutil -d sql:$HOME/.pki/nssdb -N --empty-password
          certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n "reactorca-test" -i store/ca/ca.crt

          # Create Firefox policies for certificate installation
          mkdir -p /etc/firefox/policies
          echo '{"policies":{"Certificates":{"Install":["/etc/ssl/certs/ca-certificates.crt"]}}}' > /etc/firefox/policies/policies.json

      - name: Create Caddyfile for all certificate combinations
        run: |
          # Generate Caddyfile with all certificate combinations using loops
          {
            for key_algo in $KEY_ALGORITHMS; do
              for hash_algo in $HASH_ALGORITHMS; do
                cert_name=$(echo "${key_algo}-${hash_algo}" | tr '[:upper:]' '[:lower:]')
                cert_type_header="${key_algo}-${hash_algo}"

                cat << EOF
          ${cert_name}.localhost:8443 {
              tls /var/lib/test/certs/${cert_name}.crt /var/lib/test/certs/${cert_name}.key
              root * /var/lib/test/caddy/site
              file_server
              header {
                  Strict-Transport-Security "max-age=31536000; includeSubDomains"
                  X-Frame-Options "DENY"
                  X-Content-Type-Options "nosniff"
                  X-Cert-Type "${cert_type_header}"
              }
              log {
                  output stdout
                  format console
              }
          }

          EOF
              done
            done
          } > /var/lib/test/caddy/Caddyfile

      - name: Start Caddy with test config
        run: |
          # Fix permissions so Caddy can read certificate files
          chmod 644 /var/lib/test/certs/*

          # Start Caddy directly with our test config (no systemd in container)
          cd /var/lib/test/caddy
          caddy start --config Caddyfile
          sleep 2

      - name: Capture curl version (for curl tests only)
        if: matrix.browser == 'curl'
        run: |
          cd /var/lib/test
          echo "=== Capturing curl version ==="
          BROWSER_VERSION=$(curl --version | head -1 | awk '{print $2}')
          echo "Browser version: $BROWSER_VERSION"
          echo "BROWSER_VERSION=$BROWSER_VERSION" >> $GITHUB_ENV

      - name: Test HTTPS connections - ${{ matrix.browser }}
        env:
          HOME: /root
        run: |
          cd /var/lib/test

          echo "=== Testing all certificate combinations with ${{ matrix.browser }} ==="

          # Create results directory
          mkdir -p test-results

          # Initialize results file with version info
          if [ "${{ matrix.browser }}" = "curl" ]; then
            # For curl, use the captured version
            echo '{"browser": "${{ matrix.browser }}", "version": "'$BROWSER_VERSION'", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "results": []}' > test-results/${{ matrix.browser }}-results.json
          else
            # For browsers, initialize with unknown - the JS script will populate the actual version
            echo '{"browser": "${{ matrix.browser }}", "version": "unknown", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "results": []}' > test-results/${{ matrix.browser }}-results.json
          fi

          # Generate certificate combinations dynamically
          CERT_COMBINATIONS=""
          for key_algo in $KEY_ALGORITHMS; do
            for hash_algo in $HASH_ALGORITHMS; do
              cert_name=$(echo "${key_algo}-${hash_algo}" | tr '[:upper:]' '[:lower:]')
              CERT_COMBINATIONS="$CERT_COMBINATIONS $cert_name"
            done
          done

          if [ "${{ matrix.browser }}" = "curl" ]; then
            # Test with curl (validate cert against our CA)
            echo "Testing with curl..."

            for cert in $CERT_COMBINATIONS; do
              echo "\n=== Testing $cert with curl ==="

              # Test the certificate
              if curl --cacert store/ca/ca.crt -v "https://$cert.localhost:8443/" > "curl-output-$cert.txt" 2>&1; then
                if grep -q "ReactorCA HTTPS Test" "curl-output-$cert.txt"; then
                  echo "[PASS] $cert: HTTPS connection successful with curl"

                  # Get certificate details
                  CERT_INFO=$(openssl s_client -connect localhost:8443 -servername "$cert.localhost" < /dev/null 2>/dev/null | openssl x509 -text -noout | grep -E "(Subject:|Issuer:|Public Key Algorithm:|Signature Algorithm)" | head -10)

                  # Add to results
                  jq --arg cert "$cert" --arg status "PASS" --arg info "$CERT_INFO" '.results += [{"certificate": $cert, "status": $status, "details": $info}]' test-results/${{ matrix.browser }}-results.json > tmp.json && mv tmp.json test-results/${{ matrix.browser }}-results.json
                else
                  echo "[FAIL] $cert: Content not found"
                  jq --arg cert "$cert" --arg status "FAIL" --arg error "Content not found" '.results += [{"certificate": $cert, "status": $status, "error": $error}]' test-results/${{ matrix.browser }}-results.json > tmp.json && mv tmp.json test-results/${{ matrix.browser }}-results.json
                fi
              else
                echo "[FAIL] $cert: Connection failed"
                ERROR_MSG=$(tail -5 "curl-output-$cert.txt" | tr '\n' ' ')
                jq --arg cert "$cert" --arg status "FAIL" --arg error "$ERROR_MSG" '.results += [{"certificate": $cert, "status": $status, "error": $error}]' test-results/${{ matrix.browser }}-results.json > tmp.json && mv tmp.json test-results/${{ matrix.browser }}-results.json
              fi
            done
          else
            # Test with real browser
            echo "Testing with ${{ matrix.browser }} browser..."

            # Run the enhanced browser test that tests all combinations
            node $GITHUB_WORKSPACE/.github/workflows/support/browser-test.js ${{ matrix.browser }} || true
          fi

          # Display final results summary
          echo "\n=== Final Results Summary for ${{ matrix.browser }} ==="
          if [ -f "test-results/${{ matrix.browser }}-results.json" ]; then
            jq -r '.results[] | "\(.certificate): \(.status)"' "test-results/${{ matrix.browser }}-results.json"

            # Count pass/fail
            PASS_COUNT=$(jq '.results | map(select(.status == "PASS")) | length' "test-results/${{ matrix.browser }}-results.json")
            FAIL_COUNT=$(jq '.results | map(select(.status == "FAIL")) | length' "test-results/${{ matrix.browser }}-results.json")
            echo "\nSummary: $PASS_COUNT passed, $FAIL_COUNT failed"
          fi

      - name: Validate all certificates against CA
        run: |
          cd /var/lib/test

          echo "=== Validating all certificates against CA ==="

          # Generate certificate combinations dynamically
          CERT_COMBINATIONS=""
          for key_algo in $KEY_ALGORITHMS; do
            for hash_algo in $HASH_ALGORITHMS; do
              cert_name=$(echo "${key_algo}-${hash_algo}" | tr '[:upper:]' '[:lower:]')
              CERT_COMBINATIONS="$CERT_COMBINATIONS $cert_name"
            done
          done

          VALIDATION_PASSED=0
          VALIDATION_FAILED=0

          for cert in $CERT_COMBINATIONS; do
            echo "\n=== Validating $cert ==="

            # Verify certificate chain
            if openssl verify -CAfile store/ca/ca.crt "certs/$cert.crt"; then
                echo "[PASS] $cert validates against CA"
                VALIDATION_PASSED=$((VALIDATION_PASSED + 1))

                # Show certificate details
                echo "Certificate details for $cert:"
                openssl x509 -in "certs/$cert.crt" -text -noout | grep -E "(Subject:|Issuer:|Public Key Algorithm:|Signature Algorithm:|Subject Alternative Name)" | head -10
            else
                echo "[FAIL] $cert validation failed"
                VALIDATION_FAILED=$((VALIDATION_FAILED + 1))
            fi
          done

          echo "\n=== Certificate Validation Summary ==="
          echo "Certificates passed validation: $VALIDATION_PASSED"
          echo "Certificates failed validation: $VALIDATION_FAILED"

          # Don't fail the workflow if some certificates fail validation
          # We want to collect all results
          if [ $VALIDATION_FAILED -gt 0 ]; then
            echo "Warning: Some certificates failed validation, but continuing to collect results"
          fi

      - name: Upload test results JSON
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: /var/lib/test/test-results/*.json
        if: always()

      - name: Validate RSA2048-SHA256 support
        run: |-
          cd /var/lib/test

          echo "=== Validating RSA2048-SHA256 support for ${{ matrix.browser }} ==="

          # Check if RSA2048-SHA256 test passed
          if [ -f "test-results/${{ matrix.browser }}-results.json" ]; then
            RSA2048_SHA256_STATUS=$(jq -r '.results[] | select(.certificate == "rsa2048-sha256") | .status' "test-results/${{ matrix.browser }}-results.json")

            if [ "$RSA2048_SHA256_STATUS" = "PASS" ]; then
              echo "RSA2048-SHA256 support: PASSED"
            else
              echo "RSA2048-SHA256 support: FAILED"
              echo "Error details:"
              jq -r '.results[] | select(.certificate == "rsa2048-sha256") | .error // "No error details available"' "test-results/${{ matrix.browser }}-results.json"
              echo ""
              echo "WORKFLOW FAILURE: ${{ matrix.browser }} does not support RSA2048-SHA256"
              exit 1
            fi
          else
            echo "No test results found for ${{ matrix.browser }}"
            echo "WORKFLOW FAILURE: Unable to validate RSA2048-SHA256 support"
            exit 1
          fi
